import argparse
from pathlib import Path

import e2me


BASE_DIR = Path(__file__).resolve().parent
DEFAULT_UPDATE_EMAIL_PATH = BASE_DIR / "new_update.txt"
DEFAULT_SUBJECT = "New Paper Alert"


def parse_update_email(path: Path) -> tuple[str, str] | None:
    if not path.exists():
        return None

    content = path.read_text(encoding="utf-8").strip()
    if not content:
        return None

    first_line, separator, body = content.partition("\n")
    if first_line.startswith("Subject:"):
        subject = first_line.removeprefix("Subject:").strip() or DEFAULT_SUBJECT
        return subject, body.strip()

    return DEFAULT_SUBJECT, content if not separator else f"{first_line}\n{body}".strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Send the update email generated by build-cache.py.")
    parser.add_argument(
        "--file",
        default=str(DEFAULT_UPDATE_EMAIL_PATH),
        help="Path to the generated update email text file.",
    )
    args = parser.parse_args()

    update_path = Path(args.file)
    parsed = parse_update_email(update_path)
    if not parsed:
        print(f"No update email content found at {update_path}.")
        return

    subject, body = parsed
    if not body:
        print(f"Update email body is empty in {update_path}.")
        return

    e2me.send_email(subject, body)
    print(f"Notification email sent from {update_path}.")


if __name__ == "__main__":
    main()
